server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testgroup?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  #   config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.piter.mybatisplus.entity
  #扫描项目下类型转换的包
  type-handlers-package: com.piter.mybatisplus.utils


