server:
  port: 7900
spring:
  application:
    name: provider-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

logging:
  level:
    root: INFO
